## Coding Exercise 0201

### 1. NumPy library:

#### 1.1. NumPy basics:

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [7]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
arr3 = arr1
arr4 = arr1.copy()
arr5 = arr1.view()
print("\nid(arr1) : ", id(arr1))
print("\nid(arr2) : ", id(arr2))
print("\nid(arr3) : ", id(arr3))
print("\nid(arr4) : ", id(arr4))
print("\nid(arr5) : ", id(arr5))
arr1[0] = 0
arr3[1] = 33
arr4[2] = 44
arr5[3] = 55
print("\narr1 : ", arr1)
print("\narr3 : ", arr3)
print("\narr4 : ", arr4)
print("\narr5 : ", arr5)



id(arr1) :  139856676129648

id(arr2) :  139856676128688

id(arr3) :  139856676129648

id(arr4) :  139856676129248

id(arr5) :  139856676129168

arr1 :  [ 0 33  5 55  9]

arr3 :  [ 0 33  5 55  9]

arr4 :  [ 1  3 44  7  9]

arr5 :  [ 0 33  5 55  9]


In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
arr3 = arr1

In [14]:
id(arr1)

139710092299440

In [6]:
id(arr3)

139710092299440

In [7]:
arr4 = arr1.copy()
arr5 = arr1.view()

In [15]:
id(arr4)

139710073060128

In [12]:
arr5 = arr1.view()

In [17]:
id(arr5)

139710073189520

In [ ]:
print("arr1")

#### 1.2. Creating NumPy arrays:

numpy.arange() function:

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [13]:
arr = np.arange(10) 

In [14]:
len(arr)

10

In [16]:
arr.size 

10

In [17]:
import numpy as np                                                      

a = np.arange(36).reshape(2, 3, -1)                                     
print(a)
print("\na.shape : ", a.shape)
print("\na.size : ", a.size)
print("\nlen(a) : ", len(a)) # len gives the length of the first dimension.


[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]

a.shape :  (2, 3, 6)

a.size :  36

len(a) :  2


numpy.linspace() function:

In [18]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
arr = np.linspace(0, 10, 5, retstep=True) #If True, return (samples, step), where step is the spacing between samples.
print(arr)
print(type(arr))

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
<class 'tuple'>


In [21]:
arr[0]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
arr[1]

2.5

numpy.zeros() and numpy.ones() functions:

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0])

In [26]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [28]:
arr = np.ones((2,3), dtype ='int_')

In [29]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
arr.dtype

dtype('int64')

In [31]:
arr.astype('float32') # casting

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Data type:

In [32]:
arr1 = np.array([111, 2.3,  True, False, False]) 
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [33]:
arr2 = np.array([111, 2.3, 'python', 'abc']) 
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [34]:
arr3 = np.array([111, True, 'abc']) 
arr3

array(['111', 'True', 'abc'], dtype='<U21')

#### 1.3. Indexing and slicing NumPy arrays:

In [65]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [66]:
a[-1]

5

In [67]:
a[:]

array([1, 2, 3, 4, 5])

In [68]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
a[1]

array([4, 5, 6])

In [70]:
a[-1]

array([7, 8, 9])

In [71]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a[2][1]

8

In [73]:
a[2,1]

8

In [74]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [75]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing:

In [49]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 ) 
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [50]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

#### 1.4. NumPy attributes and reshaping:

In [76]:
print(a)
a.size

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [77]:
a.shape

(3, 3)

In [78]:
a.ndim

2

Change the shape with reshape() method:

In [79]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
# reshape() just produced a 'view'.
# So, there is no permanent change to 'a'.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [83]:
a = a.reshape((2,2))
a

array([[2, 5],
       [1, 3]])

Careful that the reshape() method does not create a new object!

In [84]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999

In [85]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [86]:
# Make a copy in order to create a new object.
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

#### 1.5. Modifying NumPy arrays:

Appending elements, rows and columns to arrays:

In [87]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [88]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [94]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

Deleting array elements, rows and columns:

In [98]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(np.delete(a, 0))  # Return a new array with sub-arrays along an axis deleted. For a one dimensional array

[2 3 4 5 6]


In [99]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [100]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [101]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6]])