## Coding Exercise #0202

### 1. NumPy array operations:

#### 1.1. '+' and '*' operators for Python lists:

In [2]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
a + a

[1, 2, 3, 1, 2, 3]

In [4]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
b = np.array([1, 2, 3])
print(b)

[1 2 3]


In [10]:
b*3

array([3, 6, 9])

In [11]:
b + b

array([2, 4, 6])

In [12]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [16]:
a+b

array([5, 7, 9])

In [17]:
a-b

array([-3, -3, -3])

In [18]:
a*b

array([ 4, 10, 18])

In [19]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 1.3. Universal functions:

In [20]:
x = np.array([0, 1, 2, 3, 4, 5])

In [21]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [22]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [23]:
type(np.sqrt)

numpy.ufunc

In [24]:
type(np.exp)

numpy.ufunc

#### 1.4. NumPy functions:

In [3]:
#np.random.seed(123)
a = np.random.randint(1, 500, size=100)
print(a)

[220 421 376  10 351 207 354   9 457 183 277 197 476 113 461  35 413 320
  85 411 230 233 350 132 352  85 129 264  57 372 265 156  77 363  94 286
 335 358 213 262 425 111 459  61 246 173  76 389 458 182 466 438 237 124
 410 441 353 141 425 127   8 419 491 237 255 455  13 433  43 434 451 172
 150  37  95 136 336  55 408 161 170 147 337 258  68 234  65 196 164 190
 449 106 169 159  78 407 295 252 353 464]


In [4]:
len(np.unique(a))

96

In [5]:
np.median(a) #The median is the middle number in a sorted, ascending or descending, list of numbers 

237.0

In [6]:
np.sort(a)
print(a)

[220 421 376  10 351 207 354   9 457 183 277 197 476 113 461  35 413 320
  85 411 230 233 350 132 352  85 129 264  57 372 265 156  77 363  94 286
 335 358 213 262 425 111 459  61 246 173  76 389 458 182 466 438 237 124
 410 441 353 141 425 127   8 419 491 237 255 455  13 433  43 434 451 172
 150  37  95 136 336  55 408 161 170 147 337 258  68 234  65 196 164 190
 449 106 169 159  78 407 295 252 353 464]


In [7]:
np.sum(a)

25081

In [9]:
#variance is the expectation of the squared deviation of a random variable from its population mean or sample mean
np.round(np.var(a),2)   #Compute the variance along the specified axis.

20337.07

In [10]:
np.round(np.mean(a),2)    #Average

250.81

In [11]:
np.round(np.std(a),2) #Compute the standard deviation along the specified axis.

142.61

In [12]:
np.max(a)

491

In [13]:
np.min(a)

8

#### 1.5. Statistical methods of NumPy arrays:

In [22]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
x.sum()

55

In [17]:
x.mean()

5.5

In [18]:
x.std()

2.8722813232690143

In [19]:
x.var()

8.25

In [20]:
x.cumsum()    #Return the cumulative sum of the elements along a given axis.

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [25]:
y = np.arange(1,13)
y = y.reshape((3,-1))
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(y.mean(axis=0))

[5. 6. 7. 8.]


In [27]:
print(y.mean(axis=1))

[ 2.5  6.5 10.5]


In [41]:
z = np.random.randint(10,size=1000)

In [29]:
z.max()

9

In [32]:
z.min()

0

In [39]:
a = [z>5]
a

[array([False,  True, False, False,  True,  True, False,  True, False,
         True, False, False, False, False,  True, False,  True, False,
        False, False, False,  True, False,  True, False,  True,  True,
         True,  True, False,  True, False, False, False,  True, False,
        False, False,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True, False,  True, False,  True, False,
        False, False,  True, False,  True, False, False,  True, False,
         True,  True,  True,  True, False, False, False, False,  True,
        False,  True,  True,  True,  True, False, False, False, False,
        False, False, False,  True, False, False, False, False,  True,
        False,  True, False, False, False,  True, False,  True, False,
        False,  True,  True,  True,  True,  True, False, False,  True,
        False,  True, False,  True, False, False, False, False, False,
        False, False,  True,  True,  True, False, False,  True,  True,
      

In [36]:
(z > 5).sum()
#print(True+True+True+True+False+False+False+False)

415

In [42]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [47]:
a.argmax()

4

In [48]:
a.argmin()

1