## Coding Exercise #0203

### 1. Doing linear algebra with NumPy arrays:

In [3]:
import numpy as np

#### 1.1. Vectors:

In [5]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])

In [6]:
x + y

array([ 3,  7, 11])

In [7]:
x - y

array([-1, -1, -1])

The following operations are possible in NumPy but not in linear algebra:

In [8]:
x * y

array([ 2, 12, 30])

In [9]:
x / y

array([0.5       , 0.75      , 0.83333333])

Internal product with dot():

In [10]:
np.dot(x,y)

44

In [11]:
x.dot(y)

44

In [12]:
y.dot(x)

44

In [13]:
np.sum(x*y)

44

#### 1.2. Creating matrices:

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.random.seed(222)
np.random.random((2,2)) #np.random.random return random floats in the half-open interval [0.0, 1.0). 

array([[0.46622141, 0.11836775],
       [0.07395756, 0.90077418]])

In [55]:
#np.random.seed(111)
np.random.randn(2,2)   #Return a sample (or samples) from the “standard normal” distribution

array([[-1.44058512,  0.77370311],
       [-1.02796733, -0.09098625]])

In [57]:
np.diag([1,2,3]) #extract a diagonal or construct a diagonal array.

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [62]:
x = np.random.randint(100, size=(3,5))
print(x)
np.diag(x)

[[83 69 91 58 48]
 [95  8 50 82 40]
 [ 1 33 19 24 29]]


array([83,  8, 19])

#### 1.3. Matrix operations:

Matrix addition, subtraction and multiplication:

In [4]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])
m2 = np.array([[6, 5, 4],[3, 2, 1]])

In [5]:
m1 + m2

array([[7, 7, 7],
       [7, 7, 7]])

In [6]:
m1 - m2

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [7]:
np.transpose(m2)

array([[6, 3],
       [5, 2],
       [4, 1]])

Matrix multiplication with dot():

In [8]:
np.dot(m1,np.transpose(m2))

array([[28, 10],
       [73, 28]])

In [13]:
x = np.array([1, 3, 5])
y = np.array([2, 4, 6])
x = x.reshape((3,1))
y = y.reshape((1,3))
print("{}".format(x))
print(" ----------")
print("{}".format(y))
print("------------------")
print(x)
print(" ----------")
print(y)

[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]
------------------
[[1]
 [3]
 [5]]
 ----------
[[2 4 6]]


In [17]:
y.dot(x)[0,0]

44

In [18]:
y.dot(x)

array([[44]])

In [19]:
x.dot(y)

12

The following operations are possible in NumPy but not in linear algebra:

In [23]:
print(m1,"\n")
print(m2,"\n")
print(m1 * m2)

[[1 2 3]
 [4 5 6]] 

[[6 5 4]
 [3 2 1]] 

[[ 6 10 12]
 [12 10  6]]


In [24]:
m1 / m2

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

Operations involving matrix and scalar:

In [26]:
m = np.array([[1, 2],[3, 4]])
print(m)

[[1 2]
 [3 4]]


In [27]:
m*3

array([[ 3,  6],
       [ 9, 12]])

In [28]:
m/2

array([[0.5, 1. ],
       [1.5, 2. ]])

#### 1.4. Inverse matrix and system of linear equations:

Calculating the inverse matrix:

In [32]:
m = np.array([[1, 2],[3, 4]])
print(m,"\n")
minv = np.linalg.inv(m)   #Compute the (multiplicative) inverse of a matrix.
                          #Given a square matrix a, return the matrix ainv satisfying dot(a, ainv) = dot(ainv, a) = eye(a.shape[0]).
minv

[[1 2]
 [3 4]] 



array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
mres = np.dot(m, minv)
np.round(mres,2) 
print(mres)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [44]:
mres = np.dot(minv, m)
np.round(mres,2)

array([[1., 0.],
       [0., 1.]])

System of linear equations (number of equations = number of unknowns):

In [46]:
A = np.array([[5, 8],[6, 4]])
b = np.array([[30], [25]])
Ainv = np.linalg.inv(A)
print(np.dot(Ainv,b))

[[2.85714286]
 [1.96428571]]


In [48]:
np.linalg.solve(A, b)       #Solve a linear matrix equation, or system of linear scalar equations.

array([[2.85714286],
       [1.96428571]])

In [52]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = x = np.linalg.solve(a, b)
print(np.dot(a,x))

[1. 2.]
